### PR TITLE
Unify config key and section names

### PR DESCRIPTION
**Pull request by maringuu**
This is a cherry-pick of 3e4f460d from #749.

### CODE REVIEW

**Review by jstucke — COMMENTED** [review]
Looks good to me but there are still some failing tests:
- `src/plugins/analysis/strings/test/test_plugin_strings.py::TestAnalysisPlugInPrintableStrings::test_get_min_length_from_config`
- `src/test/unit/helperFunctions/test_program_setup.py::test_load_config`
- `src/test/unit/helperFunctions/test_program_setup.py::test_program_setup`

**Comment by maringuu** [comment]
Tests are fixed now.

**Comment by jstucke** [comment]
A problem with the linter plugin installation currently leads to failing CI builds. Once #777 is merged, it should work

**Comment by maringuu** [comment]
So should I leave this untouched and wait until master/#777 is merged in database-migration again?

**Comment by jstucke** [comment]
> So should I leave this untouched and wait until master/#777 is merged in database-migration again?

#777 was merged into master, I merged master into database-migration and database-migration into this branch and started the CI. It really sounds like we should try to merge everything back to master soon :sweat_smile:

**Pull request merged**
