### PR TITLE
crypto hints: Use plugin.PluginV0

### PR DESCRIPTION
**Pull request by maringuu**
Depends on #987

### CODE REVIEW

**Comment by maringuu** [comment]
Converting to draft as this will definitely break the schema.

**Comment by maringuu** [comment]
Despite the missing database migration this is ready!

**Comment by maringuu** [comment]
I'll leave out the database migration.
The frontend will show a message that the analysis is outdated and we can just rerun it.
@jstucke Agree? This is what we discussed iirc.

**Comment by maringuu** [comment]
https://github.com/fkie-cad/FACT_core/actions/runs/5574661620

**Comment by maringuu** [comment]
https://github.com/fkie-cad/FACT_core/actions/runs/5575210844

**Review by jstucke — COMMENTED** [review]
In some cases the matching strings appear as strings instead of hex strings (which was not the case in the old version). This can lead to some rather odd results in the web interface:
image
I'm guessing this is a problem of the YARA addon or compat class and not the plugin.

Apart from that, everything looks fine

**Review by jstucke — APPROVED** [review]

**Pull request merged**
