### PR TITLE
applied new file tree theme to comparison page

### PR DESCRIPTION
**Pull request by jstucke**
applied the new file tree theme from the analysis page to the comparison page

### CODE REVIEW

**Comment by maringuu** [comment]
LGTM! Just one question before merging: Would is somehow be possible to do this in a way that we only have to change one thing to affect both places?
This prevents oversights like this in the future.

**Comment by maringuu** [comment]
What about adding a comment to both places reminding us to not forget the other one?

**Comment by jstucke** [comment]
I looked at the code again and found enough common parts to justify a common module. I think the code also is much clearer now.

**Review by maringuu — APPROVED** [review]
LGTM. CI failure is unrelated. I probably still will wait for it to be fixed before merging.

**Pull request merged**
