### PR TITLE
fix multiple newly discovered postgres DB migration issues

### PR DESCRIPTION
**Pull request by jstucke**
fixed some postgres migration issues:
- wrong "sanitize-db" name and respective gridfs exception handling
- `KeyError` in analysis result migration
- handled error that may occur when trying to migrate comparisons of deleted firmware entries

### CODE REVIEW

**Comment by maringuu** [comment]
I'm not that deep into mongo/gridfs/postgres so this LGTM but I didn't have a deeper look.
Also I can't test this since I don't have a mongodb setup anymore.

**Comment by jstucke** [comment]
> I'm not that deep into mongo/gridfs/postgres so this LGTM but I didn't have a deeper look. Also I can't test this since I don't have a mongodb setup anymore.

Well we did kinda test this in the lab while migrating a FACT instance there. So you could say we tested it there and it worked (eventually). :sweat_smile:

**Comment by jstucke** [comment]
Maybe we could use a migration test setup but that could also be a lot of work (and I don't know if it's worth the effort)

**Comment by maringuu** [comment]
> Maybe we could use a migration test setup but that could also be a lot of work (and I don't know if it's worth the effort)

Hmm, good idea/question. I don't think its necessary as probably not that many people use FACT in production, do they?

**Comment by jstucke** [comment]
> So this can be merged?

Probably I guess? The migration on the respective PC was successful after the changes. I don't think anyone of our team still has a MongoDB instance and could also try it out.

**Review by maringuu — APPROVED** [review]

**Pull request merged**
