### PR TITLE
Improve Fedora support

### PR DESCRIPTION
**Pull request by juju4**
This should fix most issues on Fedora

* nginx: fix selinux context for etc and log files
* mongodb: use current 4.2
* remove pip-installed setuptools as seems to break selinux tools...

### CODE REVIEW

**Comment by jstucke** [comment]
Hi and thank you for your contribution! The problem is that we can't really switch to a newer version of MongoDB because of its problematic license. Since the last version which still uses the AGPL license has reached its end of life, we will probably move away from MongoDB altogether in the long term.

**Comment by juju4** [comment]
no problem. reverted mongodb part

**Review by jstucke — APPROVED** [review]
Looks good to me and the CI build passed.

**Comment by juju4** [comment]
Thanks!

**Pull request merged**
