### PR TITLE
added asserts to test events and fixed test_check_collision event count

### PR DESCRIPTION
**Pull request by jstucke**

### CODE REVIEW

**Review by maringuu — CHANGES_REQUESTED** [review]
See above.

**Comment by jstucke** [comment]
I would probably be a good idea to squash the commits when merging at this point :sweat_smile:

**Comment by maringuu** [comment]
LGTM!

**Review by maringuu — APPROVED** [review]

**Comment by maringuu** [comment]
Rebased to resolve conflicts. Merging once CI succeeds.

**Pull request merged**
