### PR TITLE
advanced search: allow search on multiple plugin results

### LINKED ISSUE #1186: Advanced serach cannot intersect multiple analysis
This does not produce any results, despite there being thousands of files that match this query.
Note that it works if we leave out the query for the `file_type` plugin.
Also these kinds of queries should be documented.
```
{
    "processed_analysis.software_components.OpenSSL": {
        "$exists": "true"
    },
    "processed_analysis.software_components.OpenSSL.meta.version": {
        "$exists": "true"
    },
    "processed_analysis.file_type.mime": "application/x-executable"
}
```

### PR DESCRIPTION
**Pull request by jstucke**
resolves #1186

### CODE REVIEW

**Review by maringuu — CHANGES_REQUESTED** [review]
Please add some tests to make sure this api does not regress.
Also this lacks documentation. I'd suggest to add this alongside the examples already displayed on the advanced search pages.

**Comment by jstucke** [comment]
> Please add some tests to make sure this api does not regress. Also this lacks documentation. I'd suggest to add this alongside the examples already displayed on the advanced search pages.

I added an example to the template and a test.

**Comment by maringuu** [comment]
@dorpvom @rhelmke @jstucke Im hesitating to merge this because I'm not sure what the long term plan is with the 'advanced serach'.
Do we want to have it at all? Will it be replaced with the recently merged GraphQL API?

**Comment by jstucke** [comment]
> @dorpvom @rhelmke @jstucke Im hesitating to merge this because I'm not sure what the long term plan is with the 'advanced serach'. Do we want to have it at all? Will it be replaced with the recently merged GraphQL API?

Good question. The long term plan definitely is to replace the Advanced Search with GraphQL but we will probably leave it as deprecated for a while so that old REST scripts don't break immediately

**Comment by dorpvom** [comment]
Closing because feature will be deprecated soon.

**Pull request closed without merging**
