### PR TITLE
tests: Introduce AnalysisPluginTestConfig

### PR DESCRIPTION
**Pull request by maringuu**
In the same way that #922 lets test-cases configure the fixtures this PR will do the same for the AnalysisPlugin tests.

### CODE REVIEW

**Comment by maringuu** [comment]
CI run: https://github.com/fkie-cad/FACT_core/actions/runs/3703030532

**Comment by maringuu** [comment]
Successful ci run: https://github.com/fkie-cad/FACT_core/actions/runs/3704610110

**Comment by maringuu** [comment]
Ci run: https://github.com/fkie-cad/FACT_core/actions/runs/3740384561

**Comment by maringuu** [comment]
https://github.com/fkie-cad/FACT_core/actions/runs/3793905243

**Comment by maringuu** [comment]
https://github.com/fkie-cad/FACT_core/actions/runs/3799523347

**Comment by maringuu** [comment]
https://github.com/fkie-cad/FACT_core/actions/runs/3882537441

**Review by jstucke — APPROVED** [review]
Looks good to me

**Comment by maringuu** [comment]
https://github.com/fkie-cad/FACT_core/actions/runs/3882831207

**Comment by maringuu** [comment]
https://github.com/fkie-cad/FACT_core/actions/runs/3912112499

**Pull request merged**
