### PR TITLE
added no_text_file to software_components signatures where missing

### LINKED ISSUE #404: False positive software results
Some software signatures that target binary files miss the `no_text_file` flag (e.g. threadx, mOS, fireOS). This leads to false positives from license files a.s.o.

### PR DESCRIPTION
**Pull request by jstucke**
- added no_text_file to software_components signatures where it was missing
- fixed errors in miniigd (wrong regex) and sqlite3 (wrong logic) signatures

resolves #404

### CODE REVIEW

**Comment by maringuu** [comment]
Maybe its obvious but I think we should put the motivation behind ignoring text files to the commit message.

**Review by maringuu — CHANGES_REQUESTED** [review]
See comment above.

**Comment by jstucke** [comment]
Honestly i don't think that is necessary. We are looking for binary executables (and libraries in some cases) and text files should always be false positives. I think the only exception to this is jQuery.

**Review by maringuu — APPROVED** [review]
LGTM!

**Pull request merged**
