### PR TITLE
WIP: adding webhook

### PR DESCRIPTION
**Pull request by nstarke**
This will eventually address #441

### CODE REVIEW

**Comment by nstarke** [comment]
I am unable to view why this is failing.  As such I will move this out of draft and rely on maintainers to guide me through the review process.

**Comment by jstucke** [comment]
As I laid out in #441, some structural changes to the intercom are needed for this to work. I will try to make the needed changes in a separate branch (which you can then merge to continue working on this).

**Comment by dorpvom** [comment]
@jstucke built the bi-directional interface in the [webhook-intercom-changes](https://github.com/fkie-cad/FACT_core/tree/webhook-intercom-changes) branch. The code looks sound to me. We'll have some sort of review process on that once he's back from vacation but, that will not introduce braking changes regarding the behavior. Most likely some renaming.

So if you like you can merge that into your fork and continue on the Webhook. Joerg already included (and tested) a stub listener that you can implement.

**Comment by nstarke** [comment]
Will do, though it may take me a few days to get around to it.  Sorry for the delay, and thanks for your work getting me all set up.

**Pull request closed without merging**
